### ISSUE TITLE
Unable to clone https://github.com/spurin/diveintoansible.git

### ISSUE THREAD

**Issue by shorn89** [spurin/diveintoansible#24]
When trying to clone the repository I met with the error "fatal: unable to access 'https://github.com/spurin/diveintoansible.git/': server certificate verification failed. CAfile: none CRLfile: none"

See attached for a screen grab.

Thanks, 

Sean Horn 

![Repo Error](https://user-images.githubusercontent.com/47042991/209893145-1068167d-d3f3-43cb-bd09-0136a616787a.PNG)

**Comment by PhantomZNeuroX** [comment]
Try This: 

`hostname=XXX
port=443
trust_cert_file_location="curl-config --ca"
sudo bash -c "echo -n | openssl s_client -showcerts -connect $hostname:$port -servername $hostname \
    2>/dev/null  | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'  \
    >> $trust_cert_file_location"`

**Warning:**This adds all certificates, instead of only the Root CAs.
Blindly adding all (any) certificate to your trustStore without due diligence is not the best course of action.

The basic reason is that your computer doesn't trust the certificate authority that signed the certificate used on the server. This doesn't mean the certificate is suspicious, but it could be self-signed or signed by an institution/company that isn't in the list of your OS's list of CAs. What you have to do to circumvent the problem on your computer is telling it to trust that certificate - if you don't have any reason to be suspicious about it.

You need to check the web certificate used for your server, and add it to your </git_installation_folder>/bin/curl-ca-bundle.crt.


Hope it works!

**Comment by spurin** [comment]
Thanks @PhantomZNeuroX for adding a response on this.

To add to this, Docker is using the source machines configuration so, if there is something from a network configuration on your host machine that prevents/restricts access to certain targets then this can happen.

Often, when I see this the persons computer/laptop is a work based system and there is some kind of internet VPN, tunnelling or proxying going on which is interfering with GitHub access.

Possibly, a works proxy could be in play which is why you may not see this in the browser but, only externally (via the likes of Docker).

If this is network related and you can fix it then great, otherwise another option might be using the google cloud shell lab (which is free) at https://diveinto.com/p/playground

Let me know how this works out if you can, thanks!

**Comment by shorn89** [comment]
**Update**

So I am using a work laptop, on a VPN.  I believe this is causing most of my issues.

I did try the https://diveinto.com/p/playground and so far, so good!  I will continue to use this, and if any other issues arise, I will just use my home desktop PC.  

Thanks !!

**Comment by spurin** [comment]
Awesome! Glad to hear you've got to the bottom of this @shorn89 and, something worth knowing, with the google cloud shell environment there's an ephemeral toggle button, allowing you to keep the environment rather than it being destroyed each time (essentially, you can just skip to the docker-compose up step).  

If you're going to be using this as your main environment, it's worth playing around with this feature, will allow you to keep any local changes 😁

Best Regards


- James

**Comment by PhantomZNeuroX** [comment]
> Thanks @PhantomZNeuroX for adding a response on this.
> 
> To add to this, Docker is using the source machines configuration so, if there is something from a network configuration on your host machine that prevents/restricts access to certain targets then this can happen.
> 
> Often, when I see this the persons computer/laptop is a work based system and there is some kind of internet VPN, tunnelling or proxying going on which is interfering with GitHub access.
> 
> Possibly, a works proxy could be in play which is why you may not see this in the browser but, only externally (via the likes of Docker).
> 
> If this is network related and you can fix it then great, otherwise another option might be using the google cloud shell lab (which is free) at https://diveinto.com/p/playground
> 
> Let me know how this works out if you can, thanks!

Thank you so much for sharing your knowledge @spurin !

Glad it worked for you @shorn89 !
